### ISSUE TITLE
curriculum, dashboard 수정

### ISSUE THREAD

**Issue by skLee-HGU** [skLee-HGU/LearnTube3#2]
## Todo

- [x] playlist 수정 모달에 생성 연결
- [x] 수강신청 후 대시보드로 link 연결
- [x] 컨텐츠 마감일 표시
- [x] 강의실 생성 시 시청 시간 기능 사용 체크박스
